### Site Settings ###
title               : Janhavi Khindkar
description         : >- 
                      Machine Learning Engineer at Quantiphi <br>  
                      I am always up for discussion about Computer Vision, RL, Quantum Physics, Mathematics & Life!!! 
baseurl             : ""                     # Change to empty quotes if you are hosting your site at <your-username>.github.io directly
repository          : Jank14/Jank14.github.io    # Change to <your-username>/<your-username>.github.io (or remove it if you don't need remote projects)
remote_theme        : Jank14/portfolYOU


### Plugins ###
plugins:
  - jemoji


### Navbar Settings ###
nav_exclude:                                            # The following paths are excluded from navbar
  - pages/tags.html
  - pages/404.html
  - pages/index.md
  - pages/testblog.md
  - pages/fquotes.md
  - pages/status.md
  - pages/contact.md

  #  - pages/contact.html

### Author Info ###
author:
  name              : Janhavi Khindkar
  image             : jank.png
# behance           : your_username
# dribbble          : your_username
  email             : jkhindkar14@gmail.com  
# facebook          : your_username
  github            : jank14
# gitlab            : your_username
#  instagram         : udaygirish
#  kaggle            : udaygirish
  linkedin          : janhavi-khindkar-417323148
#  medium            : udaygirish
# soundcloud        : your_username
# spotify           : your_username
# stackoverflow     : your_user_id
# tumblr            : your_username.tumblr.com
# twitch            : your_username
#  twitter           : UdayGirishM
# vimeo             : your_username
# youtube           : your_channel_name
#  quora             : Uday-Girish-Maradana
  resume            : jank_resume.pdf
  

### Posts ###
permalink: /blog/:title


### Collections ###
collections:
  projects:
    output: true
    permalink: /projects/:name

### Disqus ###                        
disqus:        # Your website Shortname on disqus
  shortname: https-dummy3014-github-io  

### Analytics ###
analytics:
  enabled: true                                        # Set true to enable analytics
  google:
    tracking_id: UA-175164060-1


### Defaults for collections ###
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"
 

### Exclude from processing ###
exclude:
  - README.md
  - CONTRIBUTING.md
  - LICENSE
  - "*.log"
